ssrdp/crud/urls.py
from django.conf.urls import url
from crud import views


app_name = 'crud'


urlpatterns = [
    url(r'^$', views.index),
    url(r'^(?P<model_slug>[^/]*)/$', views.List.as_view()),
    url(r'^(?P<model_slug>[^/]*)/add/$', views.Create.as_view()),
    url(r'^(?P<model_slug>[^/]*)/(?P<pk>\d+)/$', views.Update.as_view()),
    url(r'^(?P<model_slug>[^/]*)/delete/(?P<pk>\d+)/$', views.Delete.as_view()),

    url(r'^(?P<model_slug>[^/]*)/(?P<key>[^/]*)-(?P<value>[^/]*)/$', views.List.as_view()),
    url(r'^(?P<model_slug>[^/]*)/(?P<key>[^/]*)-(?P<value>[^/]*)/add/$', views.Create.as_view()),
    url(r'^(?P<model_slug>[^/]*)/(?P<key>[^/]*)-(?P<value>[^/]*)/(?P<pk>\d+)/$', views.Update.as_view()),
]

ssrdp/ssrdp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from crud import urls as crudurls
from usermanagement import urls as userurls
from course import urls as courseurls
from django.http import HttpResponseRedirect
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'.*css/bootstrap-cerulean.min.css$',
        lambda request: HttpResponseRedirect(
            '/static/charisma/css/bootstrap-cerulean.min.css')),
    url(r'^user/', include(userurls)),
    url(r'^course/', include(courseurls)),
    url(r'^', include(crudurls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ssrdp/usermanagement/urls.py
from django.conf.urls import url
from usermanagement import views


app_name = 'usermanagement'


urlpatterns = [
    url(r'^logout/$', views.logout_view),
    url(r'^(?P<model_slug>[^/]*)/$', views.List.as_view()),
    url(r'^(?P<model_slug>[^/]*)/add/$', views.AddCoordinator.as_view()),
    url(r'^(?P<model_slug>[^/]*)/(?P<pk>\d+)/$', views.UpdateCoordinator.as_view()),
]

ssrdp/usermanagement/models.py
from __future__ import unicode_literals
from django.db import models
from masterdata.models import BaseContent
from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser, BaseContent):
    ROLE_CHOICES = (
        ('p', 'Participant'),
        ('co', 'Coordinator'),
        ('admin', 'Admin'),
    )
    role = models.CharField(choices=ROLE_CHOICES, max_length=100)
    email = models.EmailField(max_length=32)
    
    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.is_staff = True
        return super(UserProfile, self).save(*args, **kwargs)


class BaseUserType(BaseContent):
    user = models.OneToOneField('UserProfile', null=True)
    district = models.ManyToManyField('masterdata.District')

    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=32)
    password = models.CharField(max_length=100)

    job_role = models.ManyToManyField('course.JobRole')

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        flag = not self.pk
        super(BaseUserType, self).save(*args, **kwargs)
        if flag:
            self.user = UserProfile.objects.create_user(
                username = self.username,
                first_name = self.first_name,
                last_name = self.last_name,
                email = self.email,
                password = self.password,
                role = self.ROLE,
            )
            self.user.set_password(self.password)
            self.save()
        else:
            self.user.username = self.username
            self.user.first_name = self.first_name
            self.user.last_name = self.last_name
            self.user.email = self.email
            self.user.password = self.password
            self.user.set_password(self.password)
            self.user.save()
        return self

    def job_roles(self):
        roles = self.job_role.all()
        return ', '.join(str(i) for i in roles)

    def sectors(self):
        roles = self.job_role.all()
        sectors = set(i.skill_development_sector for i in roles)
        return ', '.join(str(i) for i in sectors)

    def districts(self):
        return ', '.join(str(i) for i in self.district.all())

    def __str__(self):
        return '%s %s (%s)' % (self.first_name, self.last_name, self.username)


class Coordinator(BaseUserType):
    ROLE = 'co'


class Participant(BaseUserType):
    coordinator = models.ForeignKey('Coordinator', blank=True, null=True)
    ROLE = 'p'
    aadhar_number = models.CharField(max_length=100)
    adhaar_image = models.ImageField(null=True)


class PanchayathRepresentative(BaseContent):
    state = models.ForeignKey('masterdata.State')
    district = models.ForeignKey('masterdata.District')
    taluk = models.ForeignKey('masterdata.Taluk')
    village = models.ForeignKey('masterdata.Village')

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)
    email = models.EmailField(max_length=32)
    adhaar_card = models.ImageField(null=True)
    date_of_birth = models.DateField()

    @staticmethod
    def filter_queryset_for_user(qs, user):
        if user.role == 'admin':
            return qs
        elif user.role == 'p':
            return qs.filter(created_by=user)

ssrdp/usermanagement/views.py
from django.contrib.auth import logout
from django.shortcuts import redirect
from crud.views import Create, Update, List
from .models import Coordinator
from course.models import JobRole
from masterdata.models import District


def logout_view(request):
    logout(request)
    return redirect('/')


class CoordinatorMixin(object):
    template_name = 'usermanagement/add-coordinator.html'

    def get_context_data(self, **kwargs):
        context = super(CoordinatorMixin, self).get_context_data(**kwargs)
        context['job_roles'] = JobRole.objects.all()
        context['districts'] = District.objects.all()
        if self.request.method == 'POST':
            context['job_role_ids'] = [int(i) for i in self.request.POST.getlist('job_role')]
            context['district_ids'] = [int(i) for i in self.request.POST.getlist('district')]
        else:
            try:
                instance = self.get_object()
            except:
                pass
            else:
                context['job_role_ids'] = [i.id for i in instance.job_role.all()]
                context['districts_ids'] = [i.id for i in instance.district.all()]
        return context


class AddCoordinator(CoordinatorMixin, Create):
    pass


class UpdateCoordinator(CoordinatorMixin, Update):
    pass

ssrdp/usermanagement/templates/usermanagement/add-coordinator.html
{% extends 'crud/base.html' %}
{% block 'content' %}
<div id="content" class="col-lg-10 col-sm-10" style="width:100%">
  <div class="row">
    <div class="box col-md-12">
      <div class="box-inner">
	<div class="box-header well" data-original-title="">
          <h2><i class="glyphicon"></i>{{ model_nicely }}</h2>
	</div>
        <div class="box-content">
          <form action="." method = "post"  enctype="multipart/form-data">{% csrf_token %}
            {% for field in form %}
            <div class="input-group col-md-4 contains-{{ field.name }}">
	      {{ field.label_tag }}{% if field.field.required %} <b>*</b>{% endif %}
              <br/>

	      {% if field.name == 'job_role' %}
	      <select multiple="multiple" id="id_job_role" name="job_role" required="">
		{% for i in job_roles %}
		<option {% if i.id in job_role_ids %}selected="selected"{% endif %} data-section="{{ i.skill_development_sector }}" value="{{ i.id }}">{{ i }}</option>
		{% endfor %}
	      </select>

	      {% elif field.name == 'district' %}
	      <select multiple="multiple" id="id_district" name="district" required="">
		{% for i in districts %}
		<option {% if i.id in districts_ids %}selected="selected"{% endif %} data-section="{{ i.state }}" value="{{ i.id }}">{{ i }}</option>
		{% endfor %}
	      </select>

	      {% else %}
              {{ field }}
	      {% endif %}

              <p style="color:red">{% if field.errors %}{{ field.errors|striptags }}{% endif %}</p>

            </div>

            {% endfor %}
            <br>
            <button type="submit" class="btn btn-primary">
	      <i class="glyphicon glyphicon-ok icon-white"></i>
	      Submit
	    </button>
	    <a href=".."><button type="button" class="btn btn-primary">
		<i class="glyphicon glyphicon-remove icon-white"></i>
		Cancel
	    </button></a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $(function() {
	$('#id_job_role').treeMultiselect({
	    sortable: true,
	    // hideSidePanel: true,
	    startCollapsed: true
	})
	$('#id_district').treeMultiselect({
	    sortable: true,
	    // hideSidePanel: true,
	    startCollapsed: true
	})
    })
</script>
{% endblock %}