ssrdp/course/urls.py
from django.conf.urls import url
from . import views


app_name = 'course'


urlpatterns = [
    url(r'^(?P<model_slug>(:?Student))/add/$', views.StudentAdd.as_view()),
    url(r'^(?P<model_slug>(:?form3))/(?P<pk>\d+)/$', views.Form3.as_view()),
    url(r'^(?P<model_slug>(:?Teacher))/add/$', views.TeacherAdd.as_view()),
    url(r'^take-test/$', views.test),
    url(r'^as_pdf/(?P<pk>\d+)/$', views.download_pdf),
]

ssrdp/crud/urls.py
from django.conf.urls import url
from crud import views


app_name = 'crud'


urlpatterns = [
    url(r'^$', views.index),
    url(r'^(?P<model_slug>[^/]*)/$', views.List.as_view()),
    url(r'^(?P<model_slug>[^/]*)/add/$', views.Create.as_view()),
    url(r'^(?P<model_slug>[^/]*)/(?P<pk>\d+)/$', views.Update.as_view()),
    url(r'^(?P<model_slug>[^/]*)/delete/(?P<pk>\d+)/$', views.Delete.as_view()),

    url(r'^(?P<model_slug>[^/]*)/(?P<key>[^/]*)-(?P<value>[^/]*)/$', views.List.as_view()),
    url(r'^(?P<model_slug>[^/]*)/(?P<key>[^/]*)-(?P<value>[^/]*)/add/$', views.Create.as_view()),
    url(r'^(?P<model_slug>[^/]*)/(?P<key>[^/]*)-(?P<value>[^/]*)/(?P<pk>\d+)/$', views.Update.as_view()),
]

ssrdp/ssrdp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from crud import urls as crudurls
from usermanagement import urls as userurls
from course import urls as courseurls
from django.http import HttpResponseRedirect
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'.*css/bootstrap-cerulean.min.css$',
        lambda request: HttpResponseRedirect(
            '/static/charisma/css/bootstrap-cerulean.min.css')),
    url(r'^user/', include(userurls)),
    url(r'^course/', include(courseurls)),
    url(r'^', include(crudurls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ssrdp/course/models.py
from __future__ import unicode_literals
from django.db import models
from masterdata.models import BaseContent
import datetime
import uuid


GENDER_CHOICES = (('0', 'Male'), ('1', 'Female'), ('2', 'Other'))


def get_upload_to(model, task):
    def func(self, filename):
        return '%s/%s/%s-%s' % (model, task, self.id, filename)
    return func


func = None


def get_photo_path(self, filename):
    return 'teacher/%s-%s' % (uuid.uuid4(), filename)


class SkillDevelopmentSector(BaseContent):
    name = models.CharField(max_length=100)

    @staticmethod
    def filter_queryset_for_user(qs, user):
        if user.role == 'admin':
            return qs
        elif user.role in ['co', 'p']:
            try:
                co = user.coordinator
            except:
                co = user.participant
            job_roles = JobRole.filter_queryset_for_user(JobRole.objects.all(), user)
            return qs.filter(id__in=job_roles.values_list('skill_development_sector', flat=True))


class JobRole(BaseContent):
    skill_development_sector = models.ForeignKey('SkillDevelopmentSector')
    name = models.CharField(max_length=100)
    class Admin:
        inlines = ["Question", ]

    @staticmethod
    def filter_queryset_for_user(qs, user):
        if user.role == 'admin':
            return qs
        elif user.role in ['co', 'p']:
            try:
                co = user.coordinator
            except:
                co = user.participant
            return qs.filter(id__in=co.job_role.values_list('id', flat=True))


class Quota(BaseContent):
    state = models.ForeignKey('masterdata.State')
    sector = models.ForeignKey('SkillDevelopmentSector')
    job_role = models.ForeignKey('JobRole')
    quota = models.PositiveIntegerField()

    def save(self, *args, **kwargs):
        self.sector = self.job_role.skill_development_sector
        return super(Quota, self).save(*args, **kwargs)

    def total_students(self):
        return Student.objects.filter(batch__quota=self).count()

    def __str__(self):
        return '%s @ %s (%s)' % (
            str(self.job_role), str(self.state), str(self.quota))


class Question(BaseContent):
    ANSWER_CHOICES = (('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'))
    job_role = models.ForeignKey('JobRole')

    question = models.CharField(max_length=200)
    option_a = models.CharField(max_length=50)
    option_b = models.CharField(max_length=50)
    option_c = models.CharField(max_length=50)
    option_d = models.CharField(max_length=50)
    answer = models.CharField(choices=ANSWER_CHOICES,
                              max_length=10)

    hindi_workaround = models.CharField(max_length=300, blank=True, null=True)

    question_hindi = models.CharField(max_length=100, blank=True, null=True)
    option_a_hindi = models.CharField(max_length=50, blank=True, null=True)
    option_b_hindi = models.CharField(max_length=50, blank=True, null=True)
    option_c_hindi = models.CharField(max_length=50, blank=True, null=True)
    option_d_hindi = models.CharField(max_length=50, blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.hindi_workaround:
            w = self.hindi_workaround.split('\t')
            w = w + [None] * (5 - len(w))
            self.hindi_workaround = None
            (self.question_hindi, self.option_a_hindi, self.option_b_hindi,
             self.option_c_hindi, self.option_d_hindi) = w
        return super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.question

    class Admin:
        list_filter = ('job_role', 'job_role__skill_development_sector')


class Batch(BaseContent):
    batch_capacity = models.PositiveIntegerField()
    course_start_date = models.DateField()
    course_end_date = models.DateField()
    course_start_timing = models.CharField(max_length=40)
    course_end_timing = models.CharField(max_length=40)

    trainer_name = models.CharField(max_length=100)
    trainer_contact_number = models.CharField(max_length=100)
    trainer_email = models.CharField(max_length=100)

    organizer_name = models.CharField(max_length=100)
    any_volunteer_name = models.CharField(max_length=100)
    contact_number_for_emergency = models.CharField(max_length=100)

    sector = models.ForeignKey('SkillDevelopmentSector')
    job_role = models.ForeignKey('JobRole')

    state = models.ForeignKey('masterdata.State')
    district = models.ForeignKey('masterdata.District')
    taluk = models.ForeignKey('masterdata.Taluk', blank=True, null=True)
    village = models.ForeignKey('masterdata.Village', blank=True, null=True)
    quota = models.ForeignKey('Quota')

    coordinator = models.ForeignKey('usermanagement.Coordinator', blank=True, null=True)

    def clean(self):
        self.job_role = self.quota.job_role
        self.sector = self.job_role.skill_development_sector

    def total_students(self):
        return Student.objects.filter(batch=self).count()

    def __str__(self):
        return '%s - %s (%s at %s, %s)' % (
            self.course_start_date, self.course_end_date,
            self.trainer_name, str(self.district), str(self.state)
        )

    @staticmethod
    def filter_queryset_for_user(qs, user):
        if user.role == 'admin':
            return qs
        elif not user.is_authenticated():
            return qs
        elif user.role in ['co', 'p']:
            try:
                co = user.coordinator
            except:
                co = user.participant
            return qs.filter(district__in=co.district.all(),
                             job_role__in=co.job_role.all())


class Student(BaseContent):
    AFFILIATED_CHOICES = (('0', 'No'), ('1', 'Yes'))
    APPLICATION_CHOICES = (
        ('0', 'Added by admin'),
        ('1', 'Applied directly'),
        ('2', 'Passed test'),
        ('3', 'Failed Test'),
    )
    PASS_FAIL_CHOICES = (
        ('0', 'Result pending'),
        ('1', 'Passed'),
        ('2', 'Failed'),
    )
    NADI_CHOICES = (
        ('0', 'Not Applicable'),
        ('1', 'Not Done'),
        ('2', 'Done'),
    )

    application_status = models.CharField(choices=APPLICATION_CHOICES, max_length=10, default='0')
    pf_status = models.CharField(choices=PASS_FAIL_CHOICES, max_length=10, default='0', verbose_name='Pass or fail')

    are_you_already_affiliated_with_art_of_living = models.CharField(
        choices=AFFILIATED_CHOICES, max_length=10)

    skill_development_sector = models.ForeignKey('SkillDevelopmentSector')
    job_role = models.ForeignKey('JobRole')
    batch = models.ForeignKey('Batch')
    # coordinator = models.ForeignKey('usermanagement.Coordinator')
    nadi_pariksha_is_done = models.CharField(choices=NADI_CHOICES, max_length=10, default='0')
    name_as_per_aadhar_card = models.CharField(max_length=100)

    # state = models.ForeignKey('masterdata.State')
    # district = models.ForeignKey('masterdata.District')
    application_date = models.DateField(default=datetime.datetime.today)
    email = models.CharField(max_length=100)

    fh_name = models.CharField(max_length=100, verbose_name="Father's or Husband's name")
    m_name = models.CharField(max_length=100, verbose_name="Mother's name")

    date_of_birth = models.DateField()
    mobile_number = models.CharField(max_length=100)
    gender = models.CharField(
        choices=GENDER_CHOICES, max_length=10)
    education = models.CharField(max_length=100)
    religion = models.CharField(max_length=100)
    caste = models.CharField(max_length=100)

    permanent_address = models.TextField()
    per_city = models.CharField(max_length=100, verbose_name="City")
    per_state = models.ForeignKey('masterdata.State', related_name='+', verbose_name="State")
    per_district = models.ForeignKey('masterdata.District', related_name='+', verbose_name="District")
    per_constituency = models.CharField(max_length=100, verbose_name="Constituency")
    per_pincode = models.PositiveIntegerField(verbose_name="Pincode")

    same_pre_per = models.BooleanField(default=False,
        verbose_name='Present address is same as permanent_address')

    present_address = models.TextField()
    pre_city = models.CharField(max_length=100, verbose_name="City")
    pre_state = models.ForeignKey('masterdata.State', related_name='+', verbose_name="State")
    pre_district = models.ForeignKey('masterdata.District', related_name='+', verbose_name="District")
    pre_constituency = models.CharField(max_length=100, verbose_name="Constituency")
    pre_pincode = models.PositiveIntegerField(verbose_name="Pincode")

    image = models.ImageField(upload_to=get_upload_to('student', 'image'),null=True,
                              verbose_name="Upload recent photo (below 500 kb)")
    adhaar_image = models.ImageField(upload_to=get_upload_to('student', 'adhaar_image'),null=True,
                              verbose_name="Upload aadhar proof (below 500 kb)")
    edu_cert_image = models.ImageField(upload_to=get_upload_to('student', 'edu_cert_image'),null=True,
                              verbose_name="Upload latest education certificate (below 500 kb)")

    other_remarks = models.TextField(null=True)

    intro_video = models.CharField(max_length=100, null=True,
                             verbose_name=("Link to short intro video (Youtube/Facebook)"))

    work_video = models.CharField(
        max_length=100, null=True, verbose_name=(
        "Link to 1 min video (job role related)"))

    pan_card_number = models.CharField(max_length=100, null=True)
    occupation = models.CharField(max_length=100, null=True)
    # Upload 3 to 5 jobrole related photos

    experiance = models.CharField(max_length=100, null=True)
    job_role_remarks = models.TextField(null=True)
    other_certificates = models.FileField(upload_to='x',
                                          null=True, blank=True)
    other_certificates_1 = models.FileField(upload_to='x', verbose_name='',

ssrdp/course/views.py
from collections import Counter
from django.http import JsonResponse
from crud.views import Create, Update
from .models import Student, Question, Response, Batch
from django.shortcuts import render
import random
import datetime
from django import forms


class StudentAdd(Create):
    def get_success_url(self):
        return '../../take-test/?student_id=%s'%self.object.id
    def form_valid(self, form):
        res = super(StudentAdd, self).form_valid(form)
        self.object.application_status = '1'
        self.object.save()
        return res

    def get_context_data(self, **kwargs):
        context = super(StudentAdd, self).get_context_data(**kwargs)
        context['overtable_template'] = 'course/progress-bar.html'
        context['progress'] = 20
        context['step'] = 1
        return context


class Form3(Update):
    def get_context_data(self, **kwargs):
        context = super(Form3, self).get_context_data(**kwargs)
        context['overtable_template'] = 'course/progress-bar.html'
        context['progress'] = 90
        context['step'] = 3
        return context

    def get_success_url(self):
        return '/'

    def form_valid(self, form):
        if not form.cleaned_data.get('acceptance'):
            form.add_error('acceptance', forms.ValidationError(
                'Please accept the terms and conditions to proceed'))
            return self.form_invalid(form)
        return super(Form3, self).form_valid(form)


class TeacherAdd(Create):
    def get_success_url(self):
        return '/?alert=Teacher added successfully'


def test(request):
    student = Student.objects.get(id=request.GET.get('student_id'))
    if request.is_ajax():
        qids = [i.strip('response[').strip(']')
                for i in request.GET
                if 'response[' in i]
        res = {i: request.GET.get('response[%s]'%i)
               for i in qids}
        evaluation = Response.create_response(student=student, res=res)
        marks = {'correct': 0, 'wrong': 0, 'skip': 0}
        marks.update(Counter([i['status'] for i in evaluation.values()]))
        return JsonResponse({
            'evaluation': evaluation,
            'marks': marks,
            'pass': marks.get('correct', 0) >= 7,
        })
    job_role = student.job_role
    questions = random.sample(list(job_role.question_set.all()), k=10)
    return render(request, 'course/test.html', locals())


def download_pdf(request, pk):
    student = Student.objects.get(id=pk)
    res = dict(student.__dict__)
    res['student'] = student
    return render(request, 'course/download_pdf.html', res)

ssrdp/course/templates/course/download_pdf.html
{% load staticfiles %}
<style>
th, td {
    padding: 2px;
}
table {
width:100%;
margin-bottom: 10px
}
table td {
    border: 1 ; width:100px; word-wrap:break-word; min-width: 100px;
}

div {
border:1px solid black;
padding: 10px
}


#wrap {
  width: 80%;
  margin: auto;
  background: #fff;
  overflow: hidden;
  padding: 15px;
  
}
</style>


<html>
  <body border="1">
    <table>
      <tr>
	<td>
	  <img alt=""  src="{% static "logo_backup.jpg" %}" />
	</td>
	<td>
	  <h2>PRE SCREENING FORM</h2>
	</td>
	<td>
	  <img alt=""  src="{% static "logo.png" %}" />
	</td>
      </tr>
    </table>
    
    <table border="1">
      <tr>
	<td>
	  Centre: {{ student.batch.district }}
	</td>
	<td>
	  Project Name: {{ student.job_role }}
	</td>
	<td>
	  Date: {{ application_date }}
	</td>
      </tr>
    </table>
    
    <p>
      <b>Welcome to Art Of Living foundation! (Please fill the form with block letters only)</b></p>
    <table border="1">
      <tr>
	<td>
	  Applicant Name:
	</td>
	<td>
	  {{ name_as_per_aadhar_card }}
	</td>
	<td>
	  <img alt=""  src="{% static "{{ image.url }}" %}" />
	</td>
      </tr>
    </table>
    
    <table border="0">
      <tr>
	<td>
	  <table border="1">
	    <tr>
	      <td>Father's Name:</td>
	      <td>{{ fh_name }}</td>
	    </tr>
	    <tr>
	      <td>Mother's Name:</td>
	      <td>{{ m_name }}</td>
	    </tr>
	    <tr>
	      <td>Date of Birth:</td>
	      <td>{{ date_of_birth }}</td>
	    </tr>
	    <tr>
	      <td>Religion:</td>
	      <td>{{ religion }}</td>
	    </tr>
	    <tr>
	      <td>Caste:</td>
	      <td>{{ caste }}</td>
	    </tr>
	  </table>
	</td>
	<td>
	  <table border="1">
	    <tr>
	      <td>Gender:</td>
	      <td>{{ student.get_gender_display }}</td>
	    </tr>
	    <tr>
	      <td>Email:</td>
	      <td>{{ email }}</td>
	    </tr>
	    <tr>
	      <td>Adhaar Card Number:</td>
	      <td>{{ aadhaar_card_number }}</td>
	    </tr>
	    <tr>
	      <td>Pan card number: </td>
	      <td>{{ pan_card_number }}</td>
	    </tr>
	    <tr>
	      <td>Age as on 1st January 2017:</td>
	      <td>0</td>
	    </tr>
	    <tr>
	      <td>Total Years of Experiance:</td>
	      <td>{{ experiance }}</td>
	    </tr>
	  </table>
	</td>
      </tr>
    </table>
    
    
    <table border="1">
      <tr>
	<td>Name as per bank pass book</td>
	<td>Bank name</td>
	<td>A/C No</td>
	<td>IFSC</td>
      </tr>
      <tr>
	<td>{{ name_as_per_bank_records }}</td>
	<td>{{ bank_name }}</td>
	<td>{{ account_number }}</td>
	<td>{{ ifsc_code }}</td>
      </tr>
    </table>
    
    <div border="1">
      <b>Permenant Address:</b> {{ permanent_address }}
    </div>
    <table border="1">
      <tr>
	<td>Pin code</td>
	<td>City</td>
	<td>District</td>
	<td>State</td>
      </tr>
      <tr>
	<td>{{ per_pincode }}</td>
	<td>{{ per_city }}</td>
	<td>{{ student.per_district }}</td>
	<td>{{ student.per_state }}</td>
      </tr>
    </table>
    
    <div border="1">
      <b>Present Address:</b> {{ present_address }}
    </div>
    <table border="1">
      <tr>
	<td>Pin code</td>
	<td>City</td>
	<td>District</td>
	<td>State</td>
      </tr>
      <tr>
	<td>{{ pre_pincode }}</td>
	<td>{{ pre_city }}</td>
	<td>{{ student.pre_district }}</td>
	<td>{{ student.pre_state }}</td>
      </tr>
    </table>
    
    
    <table border="1">
      <tr>
	<td>Mobile No</td>
	<td>Alt. Mobile no</td>
    	<td>Language</td>
	<td>Yoga Teaching Experiance</td>
    	<td>Job Role</td>
      </tr>
      <tr>
	<td>Mobile No</td>
	<td>Alt. Mobile no</td>
    	<td>Language</td>
	<td>Yoga Teaching Experiance</td>
    	<td>Job Role</td>
      </tr>
    </table>      
    <div>
	  <b>Declaration : I hereby declare that, all the information mentioned above furnished by me is correct.
	    If anything found wrong my registration is liable to cancel without refunding any amount. I also declare that I have
	    not received any reward amount earlier from any government sponsored program. My registration can be rejected
	    or cancelled  if this project is withdrawn / postpone / cancelled by the approving
	    authority.</b></div>
    
    
    <table border="1">
      
      <br>
      <tr>
	<td height="100">Signature of the candidate :</td>
	<td height="100">Signature of the coordinator :</td>
      </tr>
      
    </table>
    <br>
    <table border="1">
      <tr>
	<b>For Official Use only </b></tr>
      <tr>
	<td>Pre Training Status :</td><td></td> 
	
	
	<td>Name of the trainer :</td><td></td> 
      </tr>
      <tr>
	<td>Batch Start date :</td><td> </td>
	<td>Batch End date :</td><td> </td>
	<td>Assessment date :</td><td> </td>
      </tr>
      
      <tr>
	<td>Course Fees :</td><td> </td>
	<td>Fees paid by :</td><td> </td>
	<td>Certificate No :</td><td> </td>
      </tr>
      
      <tr>
	<td height="100">Coordinators' Feedback :</td>
	
      </tr>
      
    </table>
  </body>
</html>

ssrdp/course/templates/course/progress-bar.html
<div class="alert alert-info">
  <h3>Step {{ step }} / 3</h3>
  <div class="progress">
    <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%">
      <span class="sr-only">{{ progress }}% Complete (success)</span>
    </div>
  </div>
</div>

ssrdp/course/templates/course/test.html
{% extends 'crud/base.html' %}
{% block 'content' %}


<style>
  select {
    width: 100%;
    height: 30px
  }
</style>


<script>
    x=0
    $(function() {
	$('.show-language-english').click(function() {
	    $('.language-hindi').hide()
	    $('.language-english').show()
	})
	$('.show-language-hindi').click(function() {
	    $('.language-english').hide()
	    $('.language-hindi').show()
	})
	$('.show-language-english').trigger('click')
	
	$('.show-onfail, .show-onsuccess, .hide-initial').hide()
	
	$('.submit-button').click(function() {
	    res = {}
	    $('.answer-dropdown').each(function() {
		res[this.dataset.qid] = $(this).val()
	    })
	    $.ajax({
		type: 'GET',
		url: '.',
		data: {'student_id': {{ student.id }}, 'response': res},
		dataType: 'json',
		success: function(d) {
		    x=d
		    $('.hide-post-res').hide();
		    console.log(d)
		    if (d.pass==true) {
			$('.show-onsuccess').show()
			$('.success-msg').html('Congratulations! You have passed the test with a score '+d.marks.correct+'/10 '+' <a href="/course/form3/{{ student.id }}/" class="btn fancybox btn-xs btn-info">proceed to step 3</a>')
		    } else {
			$('.show-onfail').show()
			$('.fail-msg').html('Sorry, your score is only '+d.marks.correct+'/10.  7/10 is required to clear the test')
		    }
		    $.each(x.evaluation, function(key, value) {
			console.log('show-answer-actual-'+key)
			$('.show-answer-actual-'+key).html('Correct Answer: '+value.correct)
			$('.show-answer-actual-'+key).show()
			if (value.status=='skip') {
			    $('.show-answer-skip-'+key).show()
			} else if (value.status=='correct') {
			    $('.show-answer-correct-'+key).html('Your Answer: '+value.your)
			    $('.show-answer-correct-'+key).show()
			} else if (value.status=='wrong') {
			    $('.show-answer-wrong-'+key).html('Your Answer: '+value.your)
			    $('.show-answer-wrong-'+key).show()
			}
		    })
		}
	    })
	})
    })
</script>


<div id="content" class="col-lg-10 col-sm-10" style="width:100%">
  <div class="row">
    <div class="box col-md-12">
      <div class="box-inner">
	<div class="box-header well" data-original-title="">
          <h2>
	    <i class="glyphicon"></i>Questions for {{ job_role }}
	  </h2>
	</div>
        <div class="box-content">

	  <div class="alert alert-info">
	    <h3>Step 2 / 3</h3>
	    <div class="progress">
	      <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
		<span class="sr-only">60% Complete (success)</span>
	      </div>
	    </div>
	  </div>

	  <div class="alert alert-info hide-post-res">
	    Please answer the following questions and click "Submit my response" button to finish your registration.  Minimum 7/10 of answers should be correct for registering.
	  </div>

	  <div class="alert alert-danger show-onfail fail-msg">
	  </div>
	  <div class="alert alert-success show-onsuccess success-msg">
	  </div>

	  <div class="alert alert-info hide-post-res">
	    <button type="submit" class="btn btn-primary language-hindi show-language-english">
	      Take test in English (अंग्रेजी में परीक्षा लें)
	    </button>
	    <button type="submit" class="btn btn-primary language-english show-language-hindi">
	      Take test in Hindi (हिंदी में परीक्षा लें)
	    </button>
	    <button type="submit" class="btn btn-primary submit-button">
	      <i class="glyphicon glyphicon-ok icon-white"></i>
	      Submit my response
	    </button>
	  </div>
	  
	  <table class="table table-striped table-bordered bootstrap-datatable responsive">

	    <thead>
	      <tr>
		<th>Question</th>
		<th>Option A</th>
		<th>Option B</th>
		<th>Option C</th>
		<th>Option D</th>
		<th>Answer</th>
	      </tr>
            </thead>
	    
            <tbody>
              {% for question in questions %}
              <tr>
		<td>
		  <div class="language-english">{{ question.question }}</div>
		  <div class="language-hindi">{{ question.question_hindi }}</div>
		</td>
		<td>
		  <div class="language-english">{{ question.option_a }}</div>
		  <div class="language-hindi">{{ question.option_a_hindi }}</div>
		</td>
		<td>
		  <div class="language-english">{{ question.option_b }}</div>
		  <div class="language-hindi">{{ question.option_b_hindi }}</div>
		</td>
		<td>
		  <div class="language-english">{{ question.option_c }}</div>
		  <div class="language-hindi">{{ question.option_c_hindi }}</div>
		</td>
		<td>
		  <div class="language-english">{{ question.option_d }}</div>
		  <div class="language-hindi">{{ question.option_d_hindi }}</div>
		</td>
		<td>
		  <div class="hide-post-res">
		    <select class="answer-dropdown" data-qid="{{ question.id }}" required="">
		      <option value="" selected="selected">---------</option>
		      {% if question.option_a %}<option value="A" class="language-english">A. {{ question.option_a }}</option>{% endif %}
		      {% if question.option_b %}<option value="B" class="language-english">B. {{ question.option_b }}</option>{% endif %}
		      {% if question.option_c %}<option value="C" class="language-english">C. {{ question.option_c }}</option>{% endif %}
		      {% if question.option_d %}<option value="D" class="language-english">D. {{ question.option_d }}</option>{% endif %}
		      
		      {% if question.option_a %}<option value="A" class="language-hindi">A. {{ question.option_a_hindi }}</option>{% endif %}
		      {% if question.option_b %}<option value="B" class="language-hindi">B. {{ question.option_b_hindi }}</option>{% endif %}
		      {% if question.option_c %}<option value="C" class="language-hindi">C. {{ question.option_c_hindi }}</option>{% endif %}
		      {% if question.option_d %}<option value="D" class="language-hindi">D. {{ question.option_d_hindi }}</option>{% endif %}
		    </select>
		  </div>
		  <span class="label-success label label-default hide-initial show-answer-actual-{{ question.id }}"></span>
		  <span class="label-success label label-default hide-initial show-answer-correct-{{ question.id }}"></span>
		  <span class="label-success label label-danger  hide-initial show-answer-wrong-{{ question.id }}"></span>
		  <span class="label-default label hide-initial  hide-initial show-answer-skip-{{ question.id }}">You skipped this question</span>
		</td>
              </tr>
	      {% endfor %} 
            </tbody>
          </table>

          <div class="alert alert-success show-onsuccess success-msg">
	  </div>

	  <div class="alert alert-info hide-post-res">
	    <button type="submit" class="btn btn-primary language-hindi show-language-english">
	      Take test in English (अंग्रेजी में परीक्षा लें)
	    </button>
	    <button type="submit" class="btn btn-primary language-english show-language-hindi">
	      Take test in Hindi (हिंदी में परीक्षा लें)
	    </button>
	    <button type="submit" class="btn btn-primary submit-button">
	      <i class="glyphicon glyphicon-ok icon-white"></i>
	      Submit my response
	    </button>
	  </div>
	    
	</div>
      </div>
    </div>
  </div>
</div>
{% endblock %}