ssrdp/crud/urls.py
from django.conf.urls import url
from crud import views


app_name = 'crud'


urlpatterns = [
    url(r'^$', views.index),
    url(r'^(?P<model_slug>[^/]*)/$', views.List.as_view()),
    url(r'^(?P<model_slug>[^/]*)/add/$', views.Create.as_view()),
    url(r'^(?P<model_slug>[^/]*)/(?P<pk>\d+)/$', views.Update.as_view()),
    url(r'^(?P<model_slug>[^/]*)/delete/(?P<pk>\d+)/$', views.Delete.as_view()),

    url(r'^(?P<model_slug>[^/]*)/(?P<key>[^/]*)-(?P<value>[^/]*)/$', views.List.as_view()),
    url(r'^(?P<model_slug>[^/]*)/(?P<key>[^/]*)-(?P<value>[^/]*)/add/$', views.Create.as_view()),
    url(r'^(?P<model_slug>[^/]*)/(?P<key>[^/]*)-(?P<value>[^/]*)/(?P<pk>\d+)/$', views.Update.as_view()),
]

ssrdp/ssrdp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from crud import urls as crudurls
from usermanagement import urls as userurls
from course import urls as courseurls
from django.http import HttpResponseRedirect
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'.*css/bootstrap-cerulean.min.css$',
        lambda request: HttpResponseRedirect(
            '/static/charisma/css/bootstrap-cerulean.min.css')),
    url(r'^user/', include(userurls)),
    url(r'^course/', include(courseurls)),
    url(r'^', include(crudurls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ssrdp/course/models.py
from __future__ import unicode_literals
from django.db import models
from masterdata.models import BaseContent
import datetime
import uuid


GENDER_CHOICES = (('0', 'Male'), ('1', 'Female'), ('2', 'Other'))


def get_upload_to(model, task):
    def func(self, filename):
        return '%s/%s/%s-%s' % (model, task, self.id, filename)
    return func


func = None


def get_photo_path(self, filename):
    return 'teacher/%s-%s' % (uuid.uuid4(), filename)


class SkillDevelopmentSector(BaseContent):
    name = models.CharField(max_length=100)

    @staticmethod
    def filter_queryset_for_user(qs, user):
        if user.role == 'admin':
            return qs
        elif user.role in ['co', 'p']:
            try:
                co = user.coordinator
            except:
                co = user.participant
            job_roles = JobRole.filter_queryset_for_user(JobRole.objects.all(), user)
            return qs.filter(id__in=job_roles.values_list('skill_development_sector', flat=True))


class JobRole(BaseContent):
    skill_development_sector = models.ForeignKey('SkillDevelopmentSector')
    name = models.CharField(max_length=100)
    class Admin:
        inlines = ["Question", ]

    @staticmethod
    def filter_queryset_for_user(qs, user):
        if user.role == 'admin':
            return qs
        elif user.role in ['co', 'p']:
            try:
                co = user.coordinator
            except:
                co = user.participant
            return qs.filter(id__in=co.job_role.values_list('id', flat=True))


class Quota(BaseContent):
    state = models.ForeignKey('masterdata.State')
    sector = models.ForeignKey('SkillDevelopmentSector')
    job_role = models.ForeignKey('JobRole')
    quota = models.PositiveIntegerField()

    def save(self, *args, **kwargs):
        self.sector = self.job_role.skill_development_sector
        return super(Quota, self).save(*args, **kwargs)

    def total_students(self):
        return Student.objects.filter(batch__quota=self).count()

    def __str__(self):
        return '%s @ %s (%s)' % (
            str(self.job_role), str(self.state), str(self.quota))


class Question(BaseContent):
    ANSWER_CHOICES = (('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'))
    job_role = models.ForeignKey('JobRole')

    question = models.CharField(max_length=200)
    option_a = models.CharField(max_length=50)
    option_b = models.CharField(max_length=50)
    option_c = models.CharField(max_length=50)
    option_d = models.CharField(max_length=50)
    answer = models.CharField(choices=ANSWER_CHOICES,
                              max_length=10)

    hindi_workaround = models.CharField(max_length=300, blank=True, null=True)

    question_hindi = models.CharField(max_length=100, blank=True, null=True)
    option_a_hindi = models.CharField(max_length=50, blank=True, null=True)
    option_b_hindi = models.CharField(max_length=50, blank=True, null=True)
    option_c_hindi = models.CharField(max_length=50, blank=True, null=True)
    option_d_hindi = models.CharField(max_length=50, blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.hindi_workaround:
            w = self.hindi_workaround.split('\t')
            w = w + [None] * (5 - len(w))
            self.hindi_workaround = None
            (self.question_hindi, self.option_a_hindi, self.option_b_hindi,
             self.option_c_hindi, self.option_d_hindi) = w
        return super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.question

    class Admin:
        list_filter = ('job_role', 'job_role__skill_development_sector')


class Batch(BaseContent):
    batch_capacity = models.PositiveIntegerField()
    course_start_date = models.DateField()
    course_end_date = models.DateField()
    course_start_timing = models.CharField(max_length=40)
    course_end_timing = models.CharField(max_length=40)

    trainer_name = models.CharField(max_length=100)
    trainer_contact_number = models.CharField(max_length=100)
    trainer_email = models.CharField(max_length=100)

    organizer_name = models.CharField(max_length=100)
    any_volunteer_name = models.CharField(max_length=100)
    contact_number_for_emergency = models.CharField(max_length=100)

    sector = models.ForeignKey('SkillDevelopmentSector')
    job_role = models.ForeignKey('JobRole')

    state = models.ForeignKey('masterdata.State')
    district = models.ForeignKey('masterdata.District')
    taluk = models.ForeignKey('masterdata.Taluk', blank=True, null=True)
    village = models.ForeignKey('masterdata.Village', blank=True, null=True)
    quota = models.ForeignKey('Quota')

    coordinator = models.ForeignKey('usermanagement.Coordinator', blank=True, null=True)

    def clean(self):
        self.job_role = self.quota.job_role
        self.sector = self.job_role.skill_development_sector

    def total_students(self):
        return Student.objects.filter(batch=self).count()

    def __str__(self):
        return '%s - %s (%s at %s, %s)' % (
            self.course_start_date, self.course_end_date,
            self.trainer_name, str(self.district), str(self.state)
        )

    @staticmethod
    def filter_queryset_for_user(qs, user):
        if user.role == 'admin':
            return qs
        elif not user.is_authenticated():
            return qs
        elif user.role in ['co', 'p']:
            try:
                co = user.coordinator
            except:
                co = user.participant
            return qs.filter(district__in=co.district.all(),
                             job_role__in=co.job_role.all())


class Student(BaseContent):
    AFFILIATED_CHOICES = (('0', 'No'), ('1', 'Yes'))
    APPLICATION_CHOICES = (
        ('0', 'Added by admin'),
        ('1', 'Applied directly'),
        ('2', 'Passed test'),
        ('3', 'Failed Test'),
    )
    PASS_FAIL_CHOICES = (
        ('0', 'Result pending'),
        ('1', 'Passed'),
        ('2', 'Failed'),
    )
    NADI_CHOICES = (
        ('0', 'Not Applicable'),
        ('1', 'Not Done'),
        ('2', 'Done'),
    )

    application_status = models.CharField(choices=APPLICATION_CHOICES, max_length=10, default='0')
    pf_status = models.CharField(choices=PASS_FAIL_CHOICES, max_length=10, default='0', verbose_name='Pass or fail')

    are_you_already_affiliated_with_art_of_living = models.CharField(
        choices=AFFILIATED_CHOICES, max_length=10)

    skill_development_sector = models.ForeignKey('SkillDevelopmentSector')
    job_role = models.ForeignKey('JobRole')
    batch = models.ForeignKey('Batch')
    # coordinator = models.ForeignKey('usermanagement.Coordinator')
    nadi_pariksha_is_done = models.CharField(choices=NADI_CHOICES, max_length=10, default='0')
    name_as_per_aadhar_card = models.CharField(max_length=100)

    # state = models.ForeignKey('masterdata.State')
    # district = models.ForeignKey('masterdata.District')
    application_date = models.DateField(default=datetime.datetime.today)
    email = models.CharField(max_length=100)

    fh_name = models.CharField(max_length=100, verbose_name="Father's or Husband's name")
    m_name = models.CharField(max_length=100, verbose_name="Mother's name")

    date_of_birth = models.DateField()
    mobile_number = models.CharField(max_length=100)
    gender = models.CharField(
        choices=GENDER_CHOICES, max_length=10)
    education = models.CharField(max_length=100)
    religion = models.CharField(max_length=100)
    caste = models.CharField(max_length=100)

    permanent_address = models.TextField()
    per_city = models.CharField(max_length=100, verbose_name="City")
    per_state = models.ForeignKey('masterdata.State', related_name='+', verbose_name="State")
    per_district = models.ForeignKey('masterdata.District', related_name='+', verbose_name="District")
    per_constituency = models.CharField(max_length=100, verbose_name="Constituency")
    per_pincode = models.PositiveIntegerField(verbose_name="Pincode")

    same_pre_per = models.BooleanField(default=False,
        verbose_name='Present address is same as permanent_address')

    present_address = models.TextField()
    pre_city = models.CharField(max_length=100, verbose_name="City")
    pre_state = models.ForeignKey('masterdata.State', related_name='+', verbose_name="State")
    pre_district = models.ForeignKey('masterdata.District', related_name='+', verbose_name="District")
    pre_constituency = models.CharField(max_length=100, verbose_name="Constituency")
    pre_pincode = models.PositiveIntegerField(verbose_name="Pincode")

    image = models.ImageField(upload_to=get_upload_to('student', 'image'),null=True,
                              verbose_name="Upload recent photo (below 500 kb)")
    adhaar_image = models.ImageField(upload_to=get_upload_to('student', 'adhaar_image'),null=True,
                              verbose_name="Upload aadhar proof (below 500 kb)")
    edu_cert_image = models.ImageField(upload_to=get_upload_to('student', 'edu_cert_image'),null=True,
                              verbose_name="Upload latest education certificate (below 500 kb)")

    other_remarks = models.TextField(null=True)

    intro_video = models.CharField(max_length=100, null=True,
                             verbose_name=("Link to short intro video (Youtube/Facebook)"))

    work_video = models.CharField(
        max_length=100, null=True, verbose_name=(
        "Link to 1 min video (job role related)"))

    pan_card_number = models.CharField(max_length=100, null=True)
    occupation = models.CharField(max_length=100, null=True)
    # Upload 3 to 5 jobrole related photos

    experiance = models.CharField(max_length=100, null=True)
    job_role_remarks = models.TextField(null=True)
    other_certificates = models.FileField(upload_to='x',
                                          null=True, blank=True)
    other_certificates_1 = models.FileField(upload_to='x', verbose_name='',

ssrdp/usermanagement/models.py
from __future__ import unicode_literals
from django.db import models
from masterdata.models import BaseContent
from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser, BaseContent):
    ROLE_CHOICES = (
        ('p', 'Participant'),
        ('co', 'Coordinator'),
        ('admin', 'Admin'),
    )
    role = models.CharField(choices=ROLE_CHOICES, max_length=100)
    email = models.EmailField(max_length=32)
    
    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.is_staff = True
        return super(UserProfile, self).save(*args, **kwargs)


class BaseUserType(BaseContent):
    user = models.OneToOneField('UserProfile', null=True)
    district = models.ManyToManyField('masterdata.District')

    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=32)
    password = models.CharField(max_length=100)

    job_role = models.ManyToManyField('course.JobRole')

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        flag = not self.pk
        super(BaseUserType, self).save(*args, **kwargs)
        if flag:
            self.user = UserProfile.objects.create_user(
                username = self.username,
                first_name = self.first_name,
                last_name = self.last_name,
                email = self.email,
                password = self.password,
                role = self.ROLE,
            )
            self.user.set_password(self.password)
            self.save()
        else:
            self.user.username = self.username
            self.user.first_name = self.first_name
            self.user.last_name = self.last_name
            self.user.email = self.email
            self.user.password = self.password
            self.user.set_password(self.password)
            self.user.save()
        return self

    def job_roles(self):
        roles = self.job_role.all()
        return ', '.join(str(i) for i in roles)

    def sectors(self):
        roles = self.job_role.all()
        sectors = set(i.skill_development_sector for i in roles)
        return ', '.join(str(i) for i in sectors)

    def districts(self):
        return ', '.join(str(i) for i in self.district.all())

    def __str__(self):
        return '%s %s (%s)' % (self.first_name, self.last_name, self.username)


class Coordinator(BaseUserType):
    ROLE = 'co'


class Participant(BaseUserType):
    coordinator = models.ForeignKey('Coordinator', blank=True, null=True)
    ROLE = 'p'
    aadhar_number = models.CharField(max_length=100)
    adhaar_image = models.ImageField(null=True)


class PanchayathRepresentative(BaseContent):
    state = models.ForeignKey('masterdata.State')
    district = models.ForeignKey('masterdata.District')
    taluk = models.ForeignKey('masterdata.Taluk')
    village = models.ForeignKey('masterdata.Village')

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)
    email = models.EmailField(max_length=32)
    adhaar_card = models.ImageField(null=True)
    date_of_birth = models.DateField()

    @staticmethod
    def filter_queryset_for_user(qs, user):
        if user.role == 'admin':
            return qs
        elif user.role == 'p':
            return qs.filter(created_by=user)

ssrdp/crud/templates/crud/base.html
{% load staticfiles %}
{% load crud_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!--
        ===
        This comment should NOT be removed.
	
        Charisma v2.0.0
	
        Copyright 2012-2014 Muhammad Usman
        Licensed under the Apache License v2.0
        http://www.apache.org/licenses/LICENSE-2.0
	
        http://usman.it
        http://twitter.com/halalit_usman
        ===
      -->
    <meta charset="utf-8">
    <title>{% block title %}RPL-SSRDP{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Recognition to prior learning">
    <meta name="author" content="Vinayak Kaniyarakkal">
    
    <!-- The styles -->
    <link id="bs-css" href="{% static "charisma/css/bootstrap-cerulean.min.css" %}" rel="stylesheet">
    
    <link href="{% static "charisma/css/charisma-app.css" %}" rel="stylesheet">
    <link href="{% static "charisma/bower_components/fullcalendar/dist/fullcalendar.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/bower_components/fullcalendar/dist/fullcalendar.print.css" %}" rel='stylesheet' media='print'>
    <link href="{% static "charisma/bower_components/chosen/chosen.min.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/bower_components/colorbox/example3/colorbox.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/bower_components/responsive-tables/responsive-tables.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/css/jquery.noty.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/css/noty_theme_default.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/css/elfinder.min.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/css/elfinder.theme.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/css/jquery.iphone.toggle.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/css/uploadify.css" %}" rel='stylesheet'>
    <link href="{% static "charisma/css/animate.min.css" %}" rel='stylesheet'>
    
     <!-- 
<link href="{% static "loader/loading.css" %}" rel='stylesheet'> -->

    
    <!-- jQuery -->
    <script src="{% static "charisma/bower_components/jquery/jquery.min.js" %}"></script>
    
    <link rel="shortcut icon" href="{% static "charisma/img/favicon.ico" %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">

        


    <link  href="{% static "tree-multiselect/jquery.tree-multiselect.min.css" %}" rel='stylesheet'>
    <script src="{% static "tree-multiselect/jquery.tree-multiselect.min.js" %}"></script>

    <link  href="{% static "timepicker/timepicker.css" %}" rel='stylesheet'>
    <script src="{% static "timepicker/timepicker.js" %}"></script>
    
    <script src="{% static "table-to-csv/table2csv.js" %}"></script>

  </head>
<script>
  {% if request.user.role == 'co' %}
$(function() {
      $('.navbar-default').attr('style', 'background-image:linear-gradient(#006600, #006000);')
})
  {% elif request.user.role == 'p' %}
$(function() {
      $('.navbar-default').attr('style', 'background-image:linear-gradient(#4c0099, #4a0095);')
})
  {% elif not request.user.role %}
$(function() {
      $('.navbar-default').attr('style', 'background-image:linear-gradient(#A0A0A0, #999999);')
})
  {% endif %}
</script>
  
  <body>
<!--			
			<div id="loading">
              <img id="loading-image" src="{% static "loader/loader.gif" %}" alt="Loading..." />
                </div>

-->
    {% block 'head' %}
    <!-- topbar starts -->
    <div class="navbar navbar-default" role="navigation">
      
      <div class="navbar-inner">
	{% if request.user.is_authenticated %}
	<a href="/user/logout/">
          <div class="btn-group pull-right">
            <button class="btn btn-default">
              <i class="glyphicon glyphicon-user"></i>Logout ({{ request.user.get_role_display }} {{ request.user.first_name }})
            </button>
          </div>
	</a>
	{% else %}
	<a href="/admin/login/?next={{ request.path }}">
          <div class="btn-group pull-right">
            <button class="btn btn-default">
              <i class="glyphicon glyphicon-user"></i>Login
            </button>
          </div>
	</a>
	{% endif %}
        <ul class="collapse navbar-collapse nav navbar-nav top-menu">

	  <li>
	    <a href="/" style="padding-top: 0px; padding-bottom:0px">
	      <img alt="" style="widht: 50; height: 25" src="{% static "logo.png" %}" >
	    </a>
	  </li>
	  
	  {% for item in request.user|get_top_menu %}

	  {% if item.submenu %}
	  <li class="dropdown dropdown-submenu">
	    <a href="#" data-toggle="dropdown">
	      {{ item.name }}
	      <span class="caret"></span>
	    </a>
	      <ul class="dropdown-menu" role="menu">
	      {% for subitem in item.submenu %}
	      <li><a href="{{ subitem.url }}" target="">{{ subitem.name }}</a></li>
	      {% endfor %}
	    </ul>
	  </li>

	  {% else %}
          <li><a href="{{ item.url }}">{{ item.name }}</a></li>
	  {% endif %}

	  {% endfor %}
        </ul>
	
      </div>
    </div>
    <!-- topbar ends -->
    {% endblock %}
    <div class="ch-container">
      <div class="row">
        {% block 'content' %}{% endblock %}
      </div><!--/fluid-row-->
    </div>
    {% if alert %}
    <script>
      $(function() {
	  alert("{{ alert }}")
      })
    </script>
    {% endif %}
    <!-- external javascript -->
    
    <script src="{% static "charisma/bower_components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
    
    <!-- library for cookie management -->
    <script src="{% static "charisma/js/jquery.cookie.js" %}"></script>
    <!-- calender plugin -->
    <script src="{% static "charisma/bower_components/moment/min/moment.min.js" %}"></script>
    <script src="{% static "charisma/bower_components/fullcalendar/dist/fullcalendar.min.js" %}"></script>
    <!-- data table plugin -->
    <script src="{% static "charisma/js/jquery.dataTables.min.js" %}"></script>
    
    <!-- select or dropdown enhancer -->
    <script src="{% static "charisma/bower_components/chosen/chosen.jquery.min.js" %}"></script>
    <!-- plugin for gallery image view -->
    <script src="{% static "charisma/bower_components/colorbox/jquery.colorbox-min.js" %}"></script>
    <!-- notification plugin -->
    <script src="{% static "charisma/js/jquery.noty.js" %}"></script>
    <!-- library for making tables responsive -->
    <script src="{% static "charisma/bower_components/responsive-tables/responsive-tables.js" %}"></script>
    <!-- tour plugin -->
    <script src="{% static "charisma/bower_components/bootstrap-tour/build/js/bootstrap-tour.min.js" %}"></script>
    <!-- star rating plugin -->
    <script src="{% static "charisma/js/jquery.raty.min.js" %}"></script>
    <!-- for iOS style toggle switch -->
    <script src="{% static "charisma/js/jquery.iphone.toggle.js" %}"></script>
    <!-- autogrowing textarea plugin -->
    <script src="{% static "charisma/js/jquery.autogrow-textarea.js" %}"></script>
    <!-- multiple file upload plugin -->
    <script src="{% static "charisma/js/jquery.uploadify-3.1.min.js" %}"></script>
    <!-- history.js for cross-browser state change on ajax -->
    <script src="{% static "charisma/js/jquery.history.js" %}"></script>
    <!-- application script for Charisma demo -->
    <script src="{% static "charisma/js/charisma.js" %}"></script>
    
    <script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>

  <!--
		<script language="javascript" type="text/javascript">
 	    $(window).load(function() {
 	    $('#loading').hide();
  		});
		</script>

-->
  </body>
</html>

ssrdp/crud/templates/crud/form.html
{% extends 'crud/base.html' %}
{% block 'content' %}

{% if model_nicely == 'Student' or model_nicely == 'Candidate Registration' %}
<script>
    $(function() {
	$('#id_same_pre_per').change(function() {
	    if ($(this).prop('checked')) {
		$('.form-row-present_address').hide()
		$('.form-row-pre_city').hide()
		$('.form-row-pre_district').hide()
		$('.form-row-pre_state').hide()
		$('.form-row-pre_constituency').hide()
		$('.form-row-pre_pincode').hide()
	    } else {
		$('.form-row-present_address').show()
		$('.form-row-pre_city').show()
		$('.form-row-pre_district').show()
		$('.form-row-pre_state').show()
		$('.form-row-pre_constituency').show()
		$('.form-row-pre_pincode').show()
	    }
	})
	$('#id_same_pre_per').trigger('change')
	$('.submit-button').click(function() {
	    if ($('#id_same_pre_per').prop('checked')) {
		$('#id_present_address').val($('#id_permanent_address').val())
		$('#id_pre_city').val($('#id_per_city').val())
		$('#id_pre_state').val($('#id_per_state').val())
$('#id_pre_district option:eq('+$('#id_per_district').val()+')').prop('disabled', false)
$('#id_pre_district option:eq('+$('#id_per_district').val()+')').prop('selected', true)
		//$('#id_pre_state').val($('#id_per_state').val())
		//$('#id_pre_district').val($('#id_per_district').val())
		$('#id_pre_constituency').val($('#id_per_constituency').val())
		$('#id_pre_pincode').val($('#id_per_pincode').val())
	    }
	})
    })
</script>
{% endif %}


<style>
  select {
    width: 100%;
    height: 30px
  }
textarea {width: 100%;}
</style>


<script>
    function task(wrt_set) {
	$('#id_'+wrt_set.parent).change(function() {
	    parent_val=$(this).val();
	    $.each($('#id_'+wrt_set.child).children(), function() {
		if((wrt_set.mapping[this.value]!=parent_val) && this.value) {
		    $(this).attr('selected', false);
		    $(this).prop('disabled', true);
		    $(this).hide();
		} else {
		    $(this).prop('disabled', false);
		    $(this).show();
		}
	    });
	    $('#id_'+wrt_set.child).trigger('change')
	})
	$('#id_'+wrt_set.parent).trigger('change')
    }

    {% for wrt_set in dropdown_wrt %}
    $(function() {
	task({{ wrt_set|safe }})
    })
    {% endfor %}
    {% block 'custom_scripts' %}
    {% endblock %}
</script>


<script>
    $(function() {
	$('input[type=text], input[type=number], input[type=email], input[type=file]').addClass('form-control')
    })
</script>


{% if datepickers %}
<script>
{% for i in datepickers %}
$(function() {
    $('#id_'+'{{ i }}').attr('readonly', true);
    $('#id_'+'{{ i }}').datepicker({'changeYear': true, 'yearRange': '1950:2020'});
})
{% endfor %}
</script>
{% endif %}


{% if timepickers %}
<script>
{% for i in timepickers %}
$(function() {
    $('#id_'+'{{ i }}').timepicker();
})
{% endfor %}
</script>
{% endif %}


<div id="content" class="col-lg-10 col-sm-10">
  <div class="row">
    <div class="box col-md-12" align="center">
      <div class="box-inner" style="width:90%">
	<div class="box-header well" data-original-title="">
          <h2><i class="glyphicon"></i>{{ model_nicely }}</h2>
	</div>
        <div class="box-content">
	  {% if overtable_template %}
	  {% include overtable_template %}
	  {% endif %}
          <form action="." method = "post" enctype="multipart/form-data">{% csrf_token %}
          <table class="table table-striped table-bordered bootstrap-datatable datatable ">
            <tbody>
              {% for field in form %}
              <tr class="form-row-{{ field.name }}">
		<td>
		  {{ field.label_tag|safe }}{% if field.field.required %} <b>*</b>{% endif %}	
		</td>
		<td>
		  {{ field }}
		  <p style="color:red">{% if field.errors %}{{ field.errors|striptags }}{% endif %}</p>
		</td>
              </tr>
	      
	      {% endfor %} 
              <tr>
		<td>
		  <button type="submit" class="btn btn-primary submit-button">
		    <i class="glyphicon glyphicon-ok icon-white"></i>
		    Submit
		  </button>
		</td>
		<td>
		  <a href="/"><button type="button" class="btn btn-primary">
		      <i class="glyphicon glyphicon-remove icon-white"></i>
		      Cancel
		  </button></a>
		</td>
              </tr>
            </tbody>
          </table>
          </form>
	  
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}